service: shoppad-api
plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  region: us-east-1
  runtime: nodejs12.x

functions:
  status:
    handler: handlers/status.handler
    events:
      - http:
          method: GET
          path: /
  getProdutosCompras:
    handler: handlers/produtos-compras/get-produtos-compras.handler
    events:
      - http:
          method: GET
          path: /produtos-compras
  postProdutosCompras:
    handler: handlers/produtos-compras/post-produtos-compras.handler
    events:
      - http:
          method: POST
          path: /produtos-compras

# only include the Prisma binary required on AWS Lambda while packaging
package:
  patterns:
    - '!node_modules/.prisma/client/query-engine-*'
    - 'node_modules/.prisma/client/query-engine-rhel-*'
